### PR TITLE
Update tls protocol

### PR DESCRIPTION
**Pull request by LeePorte**
## What

Updates the CloudFront Security Policy to the latest version as per https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html

## How to review?

Code review

### CODE REVIEW

**Comment by rjw1** [comment]
@LeePorte Is this going to get merged anytime soon? Pen testers are getting picky about some of the previous ciphers.

**Review by AP-Hunt — APPROVED** [review]

**Comment by LeePorte** [comment]
@rjw1 It's been approved and I'll get it shipped out in the morning

**Comment by rjw1** [comment]
@LeePorte thanks. I did wonder if it had just been lost down the back of the sofa.
Will this change already deployed cdn-routes?

**Comment by LeePorte** [comment]
@rjw1 It won't automatically update existing CDN routes, however if you drop support a line we can update any you like.

**Pull request merged**
